#pragma once

#include <Arduino.h>

#define DESKBUDDY_BOARD_C3 1
#define DESKBUDDY_BOARD_CLASSIC 2

#ifndef DESKBUDDY_BOARD_PROFILE
#if defined(CONFIG_IDF_TARGET_ESP32C3) || defined(ARDUINO_ESP32C3_DEV)
#define DESKBUDDY_BOARD_PROFILE DESKBUDDY_BOARD_C3
#else
#define DESKBUDDY_BOARD_PROFILE DESKBUDDY_BOARD_CLASSIC
#endif
#endif

#if DESKBUDDY_BOARD_PROFILE == DESKBUDDY_BOARD_C3
#define DESKBUDDY_SDA 8
#define DESKBUDDY_SCL 9
#define DESKBUDDY_BOARD_NAME "ESP32-C3 Super Mini"
#else
#define DESKBUDDY_SDA 21
#define DESKBUDDY_SCL 22
#define DESKBUDDY_BOARD_NAME "ESP32 DevKit"
#endif

#define DESKBUDDY_NAME "DeskBuddy"
#define DESKBUDDY_VERSION "2.0.0"
#define DESKBUDDY_HOSTNAME "deskbuddy"
#define DESKBUDDY_OLED_ADDRESS 0x3C
#define DESKBUDDY_WIDTH 128
#define DESKBUDDY_HEIGHT 64
#define DESKBUDDY_I2C_HZ 400000
#define DESKBUDDY_SETUP_IP 192,168,4,1
#define DESKBUDDY_DNS_PORT 53
#define DESKBUDDY_WIFI_TIMEOUT_MS 20000UL
#define DESKBUDDY_WIFI_RETRY_MS 10000UL
#define DESKBUDDY_OLED_FRAME_MS 83UL
#define DESKBUDDY_CLOCK_INTERVAL_MS 180000UL
#define DESKBUDDY_CLOCK_DURATION_MS 6500UL
#define DESKBUDDY_WEATHER_INTERVAL_MS 600000UL
#define DESKBUDDY_WEATHER_DURATION_MS 8000UL
#define DESKBUDDY_WEATHER_TIMEOUT_MS 4000UL
#define DESKBUDDY_NOTIFICATION_MAX 180
#define DESKBUDDY_TEXT_MAX 64
#define DESKBUDDY_SETUP_AP_PASSWORD ""
